import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from '@/component/navigation';
import { ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thanh Nguyen Portfolio",
  description: "Generated by Thanh Nguyen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        <Navigation />
        <div className="main-content flex-grow">
          <ToastContainer />
          {children}
        </div>
      </body>
    </html>
  );
}
